Develop Stream 2023-05-29 (#434)
* fix benchmark filter

* Stop relying on WIN32 in C++ (rocPRIM)

* fix block sort function signatures

fix block sort size overloads

review comments round 1

review comments round 2

extract common functionality

add clarification

* fix wrong seed value usage in tests

* Add copyright check script based on hipCUB

* standalone tests for rocprim intrinsics

test rocprim::lane_id

test rocprim::masked_bit_count

test rocprim::detail::warp_any, rocprim::detail::warp_all

test rocprim::warp_permute

rocprim::warp_permute: make sure that dst_lane properly wraps

test rocprim::warp_shuffle_xor; unify warp sort tests

add test_utils::custom_test_type<double> to default intrinsic test types

Replace rocprim::MatchAny with fixed rocprim::match_any

This function was previously broken on architectures with warp size 64.

test rocprim::match_any

intrinsic tests: replace uint64_t with max_lane_mask_type

intrinsic tests: test with not all threads active

test rocprim::ballot

integrate custom_nonaligned and custom_16aligned with other tests

add some extra comments on warp intrinsics & tests

simplify test_shuffle host-side computation

mbcnt_kernel -> masked_bit_count_kernel

* block adjacent difference: remove asserts

These asserts seem to cause a miscompilation if compiling with upstream clang
15 while not enabling -DNDEBUG, which causes some device_adjacent_difference
tests to fail.

* remove references to hcc

Remove references to HCC

Remove further references to HCC

* fix googlebenchmark version

* Removed deprecated random_shuffle

* add workaround for sdma oversubscription

* fix discarded status

* remove unused config selection case from templates

* fix configured files not getting reconfigured after clean

* Fix typos in temp_storage.hpp

* revert breaking changes for match any

* Add match based block histogram

* Fix block raking reduce for non-commutative operations

* Fix bug with excess valid items amount

* Config dispatch for transform and binary_search

* Implemented autotuning benchmarks for binary_search

* Updated autotuning configs for binary_search

* benchmark all binary search sub-algorithm

* Updated lower bound config

* Fixes

* Simplified the config of device_transform using the original config dispatch design

* Extending autotune CI options, exclude problematic benchmark

* Updated autotune config for radix sort onesweep, gfx906

* feat(device_partition): added partition_two_way

* copyright fixes

* fix wrong type deduction in block_reduce_ranking_reduce

---------

Co-authored-by: Máté Ferenc Nagy-Egri <mate@streamhpc.com>
Co-authored-by: Gergely Meszaros <gergely@streamhpc.com>
Co-authored-by: Robin Voetter <robin@streamhpc.com>
Co-authored-by: Ivan Siutsou <ivan@streamhpc.com>
Co-authored-by: Bálint Soproni <balint@streamhpc.com>
Co-authored-by: Mátyás Aradi <matyas@streamhpc.com>
Co-authored-by: Lőrinc Serfőző <lorinc@streamhpc.com>
Co-authored-by: Nara Prasetya <nara@streamhpc.com>
Co-authored-by: Beatriz Navidad Vilches <beatriz@streamhpc.com>

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -3,8 +3,27 @@
 # Redirect output to stderr.
 exec 1>&2
 
+check_failed=false
+
 # Do the code format check
 if ! "$(git rev-parse --show-toplevel)/scripts/code-format/check-format.sh" HEAD --cached 1>&2; then
+    printf "\n\033[31mFailed\033[0m: code format check.\n"
+    check_failed=true
+fi
+
+# Do the copyright check
+# update & apply copyright when hook config is set, otherwise just verify
+opts="-qc"
+if [ "$(git config --get --type bool --default false hooks.updateCopyright)" = "true" ]; then
+    opts="-qca"
+fi
+
+if ! "$(git rev-parse --show-toplevel)/scripts/copyright-date/check-copyright.sh" "$opts" 1>&2; then
+    printf "\n\033[31mFailed\033[0m: copyright date check.\n"
+    check_failed=true
+fi
+
+if $check_failed; then
     printf "
 Pre-commit check failed, please fix the reported errors.
 Note: Use '\033[33mgit commit --no-verify\033[0m' to bypass checks.\n"
