Fix install script to set cmake build type when using g flag (#147)

diff --git a/install b/install
--- a/install
+++ b/install
@@ -16,7 +16,7 @@ function display_help()
     #    echo "    [-d|--dependencies] install build dependencies"
     echo "    [-c|--clients] build library clients too (combines with -i & -d)"
     echo "    [-g|--debug] -DCMAKE_BUILD_TYPE=Debug (default is =Release)"
-    echo"     [-b|--benchmark] builds and runs benchmark"
+    echo "    [-b|--benchmark] builds and runs benchmark"
     echo "    [--hip-clang] build library for amdgpu backend using hip-clang"
 }
 
@@ -28,6 +28,7 @@ install_package=false
 build_package=false
 build_clients=false
 build_release=true
+build_type=Release
 build_hip_clang=false
 run_tests=false
 build_benchmark=false
@@ -63,40 +64,41 @@ check_exit_code( )
 
 while true; do
     case "${1}" in
-	-h|--help)
-	    display_help
-	    exit 0
-	    ;;
-	-i|--install)
-	    install_package=true
-	    shift ;;
-	-p|--package)
-	    build_package=true
-	    shift ;;
-    -r|--relocatable)
-         build_relocatable=true
-         shift ;;
-    -c|--clients)
-        build_clients=true
-        shift ;;
-	-g|--debug)
-	    build_release=false
-	    shift ;;
-	-t|--test)
-	    run_tests=true
-	    shift ;;
-    -b|--benchmark)
-        build_benchmark=true
-        shift ;;
-	--hip-clang)
-	    build_hip_clang=true
-	    shift ;;
-	--) shift ; break ;;
-	*)  echo "Unexpected command line parameter received; aborting";
-	    exit 1
-	    ;;
+        -h|--help)
+            display_help
+            exit 0
+            ;;
+        -i|--install)
+            install_package=true
+            shift ;;
+        -p|--package)
+            build_package=true
+            shift ;;
+        -r|--relocatable)
+            build_relocatable=true
+            shift ;;
+        -c|--clients)
+            build_clients=true
+            shift ;;
+        -g|--debug)
+            build_release=false
+            build_type=Debug
+            shift ;;
+        -t|--test)
+            run_tests=true
+            shift ;;
+        -b|--benchmark)
+            build_benchmark=true
+            shift ;;
+        --hip-clang)
+            build_hip_clang=true
+            shift ;;
+        --) shift ; break ;;
+        *)  echo "Unexpected command line parameter received; aborting";
+            exit 1
+            ;;
     esac
-    done
+done
 
 if [[ "${build_relocatable}" == true ]]; then
     if ! [ -z ${ROCM_PATH+x} ]; then
@@ -150,7 +152,7 @@ if [[ "${build_relocatable}" == true ]]; then
        -DBUILD_BENCHMARK=${benchmark} -DBUILD_TEST=${clients} \
        -DCMAKE_MODULE_PATH="${rocm_path}/hip/cmake" ../../.     # or cmake-gui ../.
 else
-    CXX=${rocm_path}/bin/${compiler} ${cmake_executable} -DBUILD_BENCHMARK=${benchmark} -DBUILD_TEST=${clients} ../../. # or cmake-gui ../.
+    CXX=${rocm_path}/bin/${compiler} ${cmake_executable} -DBUILD_BENCHMARK=${benchmark} -DBUILD_TEST=${clients} -DCMAKE_BUILD_TYPE=${build_type} ../../. # or cmake-gui ../.
 fi
 
 # Build
